# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [20]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
import numpy as np
x=np.zeros(15)    
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [6]:
x=np.arange(10,49) 
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [30]:
x=np.arange(10,49)
print(x.shape)

(39,)


5. Print the type of the previous array in question 3

In [31]:
x=np.arange(10,49) 
print(x.dtype)

int32


6. Print the numpy version and the configuration


In [23]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/toshiba/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/toshiba/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/toshiba/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

7. Print the dimension of the array in question 3


In [36]:
x=np.arange(10,49) 

print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. Create a boolean array with all the True values

In [35]:
np.ones((2, 2), dtype=bool)

array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [37]:
array = np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [38]:
array = np.arange(27).reshape(3,3,3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [9]:
a=np.arange(100)
print("original aaray:")
print(a)
print("reverse array:") 
a=a[::-1]
print(a)

original aaray:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
reverse array:
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [10]:
a=np.zeros(10)
a[5]=1      
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [11]:
a=np.identity(3)     
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [40]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.astype(float))

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [12]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],     

           [7., 2., 12.]])
np.multiply(arr1,arr2)


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [13]:
a= np.array([[1, 2], [3, 4]]) 
b= np.array([[1, 7], [3, 4]]) 
comparison = a == b 
c = comparison.all()    
#print(type(c))
  
print(c)

False


17. Extract all odd numbers from arr with values(0-9)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

18. Replace all odd numbers to -1 from previous array

In [16]:
arr=np.arange(10)
arr[arr%2==1]=-1       
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [17]:
a=np.arange(15)
a[5:13]=5       
a

array([ 0,  1,  2,  3,  4,  5,  5,  5,  5,  5,  5,  5,  5, 13, 14])

20. Create a 2d array with 1 on the border and 0 inside

In [18]:
x = np.ones((5,5))

x[1:-1,1:-1] = 0           
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [19]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
np.where(a<5,a,12)

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

26. Create a 10x10 array with random values and find the minimum and maximum values

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [47]:
array = np.arange(15).reshape(5,3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [44]:
array = np.arange(1,16).reshape(2,2,4)
array

ValueError: cannot reshape array of size 15 into shape (2,2,4)

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [2]:
import numpy as np
a=np.random.randint(12,size=(5))
b=np.random.randint(12,size=(5))
print(a)
print(b)
c=a.max(axis=0)
d=b.max(axis=0)
print(c)
print(d)
New_array=np.array([c,d])
New_array

[3 8 1 8 0]
[10  0  9 10  7]
8
10


array([ 8, 10])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a=np.unique(names)
print(a)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [4]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result=np.setdiff1d(a,b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [15]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])  
x@y

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum